services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ${DATA_DIR}/postgres/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - "${DATA_DIR}/redis:/data"
    expose:
      - 6379

  app:
    image: local/${SERVICENAME}
    restart: unless-stopped
    container_name: ${SERVICENAME}
    depends_on:
      - database
      - redis
    volumes:
      - ./pretix.cfg:/etc/pretix/pretix.cfg
      - ${DATA_DIR}/data:/data
    sysctls:
      net.core.somaxconn: 4096
    networks:
      - default
      - traefik
      - ldap
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - traefik.enable=true
      - traefik.docker.network=traefik
      # Https
      - traefik.http.routers.pretix-sec.entrypoints=websecure
      - traefik.http.routers.pretix-sec.rule=Host(`pretix.${DOMAINNAME}`)
      - traefik.http.routers.pretix-sec.middlewares=secheader@file
      - traefik.http.services.pretix.loadbalancer.server.port=80


networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
