services:
  database:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ${DATA_DIR}/postgres/db/16/data:/var/lib/postgresql/data
    labels:
      - com.centurylinklabs.watchtower.enable=false

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - "${DATA_DIR}/redis:/data"
    expose:
      - 6379
    labels:
      - com.centurylinklabs.watchtower.enable=false

  app:
    image: ghcr.io/mind-hochschul-netzwerk/pretix:latest
    restart: unless-stopped
    container_name: ${SERVICENAME}
    depends_on:
      - database
      - redis
    volumes:
      - ./pretix.cfg:/etc/pretix/pretix.cfg
      - ${DATA_DIR}/data:/data
    sysctls:
      net.core.somaxconn: 4096
    networks:
      - default
      - traefik
      - ldap
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICENAME}.middlewares=secheader@file
      - traefik.http.services.${SERVICENAME}.loadbalancer.server.port=80

networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
